### ISSUE TITLE
[Feature Request] Refactor to work with ansible galaxy

### ISSUE THREAD

**Issue by tvories** [opoplawski/ansible-pfsense#30] opened 2019-11-21 14:38 UTC
## Overview
I have forked this project and attempted to refactor it to work with ansible galaxy collections.  This will allow users to install this module like they would a role.  This requires Ansible 2.9+ in order to install.

## Current issues
I am working out of the `galaxy` branch of my fork https://github.com/tvories/ansible-pfsense/tree/galaxy 

I have compiled a local version of the refactored code using `ansible-galaxy build` (specifically using ansible 2.10-dev).  That gives me a tar.gz of the plugin that I can install in my ansible project using `ansible-galaxy collection install opoplawski-pfsense-1.0.0.tar.gz`.

### My playbook:

```yaml
# pfsense.yml
---

- name: Pfsense Rules
  hosts: pfsense
  become: true

  roles:
    - pfsense
```

### The role:

```yaml
# roles/pfsense/tasks/vlans.yml
---

# VLAN Configuration

- name: 192.168.1.0/24 - Legacy
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 1
    descr: 192.168.1.0/24 - Legacy
    state: present

- name: 192.168.20.0/24 - Primary
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 20
    descr: 192.168.20.0/24 - Primary
    state: present

- name: 192.168.40.0/24 - Guest WiFi
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 40
    descr: 192.168.40.0/24 - Guest WiFi
    state: present

- name: 192.168.50.0/24 - IoT
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 50
    descr: 192.168.50.0/24 - IoT
    state: present

- name: 192.168.60.0/24 - DMZ
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 60
    descr: 192.168.60.0/24 - DMZ
    state: present

- name: 192.168.70.0/24 - Joey Backup
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 70
    descr: 192.168.70.0/24 - Joey Backup
    state: present
```

### The error
The module appears to import properly after the refactoring.  When I run `ansible-playbook pfsense.yml` I get the following error:

`ansible_collections.opoplawski.pfsense.plugins.module_utils.network.pfsense.pfsense_vlan.__spec__ is None`

I am not familiar with developing ansible modules, so I'm hoping this is just a mistake on the refactoring on my part.

The full ansible output:
```
PLAY [Pfsense Rules] ***********************************************************

TASK [Gathering Facts] *********************************************************
ok: [pfsense.mcbadass.local]

TASK [pfsense : include_tasks] *************************************************
included: /ansible/playbooks/roles/pfsense/tasks/vlans.yml for pfsense.mcbadass.local

TASK [pfsense : 192.168.1.0/24 - Legacy] ***************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: ansible_collections.opoplawski.pfsense.plugins.module_utils.network.pfsense.pfsense_vlan.__spec__ is None
fatal: [pfsense.mcbadass.local]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP *********************************************************************
pfsense.mcbadass.local     : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by f-bor** [comment] 2019-11-22 05:53
I tried to reproduce the error by creating your role, collection build then  collection install, but when I run the role, I get another error on the task:
```
Could not find imported module support code for pfsense_vlan.  Looked for either PFSenseModule.py or pfsense.py
```
Are you installing the collection into a particular place ?

**Comment by tvories** [comment] 2019-11-22 16:41
I do have my collection path set to `collections_paths=collections` in my ansible.cfg.  Also, make sure you are referencing the FQCN for the plugin.  IE: `opoplawski.pfsense.pfsense_vlan` instead of `pfsense_vlan`.

**Comment by f-bor** [comment] 2019-11-22 18:44
Ok, I took a little more time to understand. I think my error message is quite the same as yours (I'm just not sure why it's looking so different).

The issue comes from the import in module_utils/network/pfsense/pfsense_vlan.py which is not refactored. It works when it is.

So it should be:
```
from ansible_collections.opoplawski.pfsense.plugins.module_utils.network.pfsense.pfsense import PFSenseModule, PFSenseModuleBase
```

Let me know if it works for you.

Also, if I may suggest a couple things:
- get rid of the module_utils sub-directories (network and so on), just put everything in module_utils
- exclude the misc and test directories
- pfsense.modules seems a better collection name imo

**Comment by tvories** [comment] 2019-11-22 19:27
I thought the same thing about removing the sub-folders.  It makes sense when it matches the ansible plugin architecture but in a contained collection it's just extra folders.

Let me try your fix.

**Comment by tvories** [comment] 2019-11-22 22:05
I just realized that if this PR gets accepted, it will require ansible 2.9+ to use this plugin.  Either that, or there will be duplicate docs for using it with galaxy or stand-alone.  Any input on that decision @opoplawski or @f-bor?  I can definitely add docs for both use cases if you think that's the best way.

**Comment by tvories** [comment] 2019-11-22 23:32
I added documentation for using ansible-galaxy as well as the previous setup.  I added a release to my repo with a zipped binary of the unmodified repo to allow people to still install the module even if they don't have ansible 2.9.

**Comment by f-bor** [comment] 2019-11-23 07:02
What I meant for the collection name was "namespace: pfsense" and "name: modules". So the wording to call pfsense_vlan would be pfsense.module.pfsense_vlan which seems natural to me (and easier to write than Orion's name :D)

For the PR, I'm not used to ansible galaxy but I would prefer a script to do the refactoring in a temporary folder and generate the archive from there. The script should be quite easy to write (grep the collection's name from galaxy.yml, copy whatever is required into the temp folder, find -exec sed the imports and launch ansible-galaxy in the end) and it would not break the existing playbooks. For the doc, it should then be an extra wiki page with a link in the project's readme.

@opoplawski any thoughts ?

**Comment by tvories** [comment] 2019-11-24 04:00
I think the namespace is tied to a user/github account, though I'm not positive on that, so I'm not sure if pfsense would be available over opoplawski. I agree that it would be much more straightforward, though.

Good ideas on the script generated refactoring, although I did found the original layout to be a bit confusing and didn't like the idea of having to run my infrastructure code inside of this repo and preferred it to be completely stand-alone.  It was difficult for me initially to install this module.  I'm definitely open to suggestions, though.

It's possible we could further refactor it and keep the playbooks working in the collection and add a role folder in addition to the plugin folder, similar to https://github.com/freeipa/ansible-freeipa .  That would keep each piece (roles and plugins) self contained but would allow for both if a user wanted to use the included roles.

**Comment by opoplawski** [comment] 2019-11-26 02:30
First, thanks for working on this.  I just haven't had any extra time recently.

I think it's time to create a github organization to host this.  We could go with a very short name (pfans?) or something like 'pfansible'.  I'm almost irresistibly drawn to 'pfsensible' as it is too cute :).  Then the project/repo name could be something like 'core', leaving open the possibility of other collections for say managing openvpn, haproxy, and other packages.    I could even see dropping the pfsense_ from the module names and so have 'pfsensible.core.rule'.

I really like the idea of building the collection via script, at least for a while to test the waters.  But I suspect that this will really be the way forward for this project.  We've gotten basically zero response to our attempts to start to move this into ansible proper.

**Comment by tvories** [comment] 2019-11-26 02:40
I wonder if we create a new repo just for the galaxy version for now and then any changes in the main repo get scripted down to the galaxy project.  I think it's good to have the galaxy release to have its own repo, as that seems to be the way to doc and request changes to it.

I also like pfsensible 🤣

**Comment by tvories** [comment] 2019-11-26 05:06
I just read up on the [ansible PR](https://github.com/ansible/ansible/pull/50390) you guys submitted to merge it into ansible base.  That makes a lot of sense now as to the way the repository was set up.  I would agree that you probably wouldn't want to totally refactor the plugin if there's a chance it would be included in ansible at some point.

Sorry for any confusion here.  I was unaware of the history of this project.  I think the downstream separate galaxy repo may be a better idea.

**Comment by f-bor** [comment] 2019-11-26 07:15
@opoplawski I think they didn't answer because of the aggregated scheme. If we remove that, merge the related files between library and module_utils, they would probably accept your PRs for the modules.

If I'm the only user of those modules (aggregate & ipsec_aggregate), it's probably the best solution. I can just write a program to regenerate the modules as they are today for my own usage.

**Comment by opoplawski** [comment] 2020-01-13 04:23
I really have no idea why ansible is not interested in my PR as there has been *zero* replies to it.  I suspect they are just overwhelmed and pfsense is not a priority for them.

I am starting to think that a galaxy collection will likely be the way forward for the foreseeable future.  I've created a new github organization (pfsensible) and a new repo (core) https://github.com/pfsensible/core.  I've also requested the pfsensible namespace in galaxy (https://github.com/ansible/galaxy/issues/2194).  I'm sad that we loose the git history in the pfsensible/core repo, but maybe this can be addressed later.  The core repo is generated via a simple script that I'll check in at some point when ready.

@tvories thanks again for getting this started!

**Comment by f-bor** [comment] 2020-01-13 07:45
Well, our approach to implement modules is quite dirty. We don't have much choice since there is no CLI or API. In the end, we have to rewrite pfSense piece by piece to implement proper parameters validation and changes. I fear the day they will do some major changes and force us to maintain different behaviours following pfSense version. It would be easier for everyone if they release a proper CLI or API.

FWIW, I don't see the point in having an organization. Enabling tags here and  having a simple packaging script would'nt be enough to push to galaxy ?

**Comment by opoplawski** [comment] 2020-01-31 02:29
Closing this.  We're going to maintain the separate repos for now.  Thank you again for getting this started.

**Closed by opoplawski** 2020-01-31 02:29 UTC
